version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./application/config/php.ini:/usr/local/etc/php/php.ini
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: codeigniter_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306/tcp
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
